(define (problem freecell-problem)
  (:domain freecell)
  (:objects
    card1 card2 card3 card4 card5 card6 card7 card8 - card
    col1 col2 col3 col4 col5 col6 col7 col8 - column
    home1 home2 home3 home4 - homecell
    free1 free2 free3 free4 - freecell
    phone1 phone2 phone3 phone4 - card
  )

  (:init
    (on-top card1 col1)
    (on-top card2 col2)
    (on-top card3 col3)
    (on-top card4 col4)
    (on-top card5 col5)
    (on-top card6 col6)
    (on-top card7 col7)
    (on-top card8 col8)
    (empty-freecell free1)
    (empty-freecell free2)
    (empty-freecell free3)
    (empty-freecell free4)
    (empty-column col5)
    (empty-column col6)
    (empty-column col7)
    (empty-column col8)
    (empty-homecell home1)
    (empty-homecell home2)
    (empty-homecell home3)
    (empty-homecell home4)
    (in-homecell phone1 home1)
    (in-homecell phone2 home2)
    (in-homecell phone3 home3)
    (in-homecell phone4 home4)
    (next-card phone1 card1)
    (next-card card1 card2)
    (next-card card2 card3)
    (next-card card3 card4)
    (next-card card4 card5)
    (next-card card5 card6)
    (next-card card6 card7)
    (next-card card7 card8)
    (same-suit card1 card2)
    (same-suit card3 card4)
    (same-suit card5 card6)
    (same-suit card7 card8)
    (opposite-color card2 card3)
    (opposite-color card4 card5)
    (opposite-color card6 card7)
  )

  (:goal
    (and
      (in-homecell card1 home1)
      (in-homecell card2 home1)
      (in-homecell card3 home2)
      (in-homecell card4 home2)
      (in-homecell card5 home3)
      (in-homecell card6 home3)
      (in-homecell card7 home4)
      (in-homecell card8 home4)
    )
  )
)
